language: java
jdk:
- oraclejdk8
before_install:
- wget https://github.com/nats-io/nats-streaming-server/releases/download/v0.2.2/nats-streaming-server-linux-amd64.zip -q
- export PATH=$PATH:${TRAVIS_BUILD_DIR}/nats-streaming-server-linux-amd64
- echo "MAVEN_OPTS='-Xmx2g -XX:+TieredCompilation -XX:TieredStopAtLevel=1'" > ~/.mavenrc
install:
#- sudo apt-get -qq update
- sudo apt-get install -y gnupg2
script:
- mvn --settings .travis/settings.xml clean verify -U
after_success:
- mvn --settings .travis/settings.xml coveralls:report
before_deploy:
- echo "decrypting keyrings"
- openssl aes-256-cbc -K $encrypted_ddc2c9dfa8f8_key -iv $encrypted_ddc2c9dfa8f8_iv
  -in .travis/keyrings/secrets.tar.enc -out .travis/keyrings/secrets.tar -d
- cd .travis/keyrings && tar xvf secrets.tar
- cd ${TRAVIS_BUILD_DIR}
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    repo: nats-io/java-nats-streaming
    branch: master
    jdk: oraclejdk8
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    repo: nats-io/java-nats-streaming
    tags: true
    jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
  - larry@apcera.com
env:
  global:
  - GPG_DIR=${TRAVIS_BUILD_DIR}/.travis/keyrings
